<?php
/**
 * JMVC ConfigWriter - Generate PHP config files from UI
 *
 * @package JMVC\Admin
 */

declare(strict_types=1);

namespace JMVC\Admin;

/**
 * Handles writing configuration files to theme
 */
class ConfigWriter
{
    /**
     * Save all configuration from form data
     *
     * @param array<string, mixed> $config
     * @return array{success: bool, error?: string}
     */
    public static function saveAll(array $config): array
    {
        $configPath = Admin::getThemeJmvcPath() . 'config/';

        if (!is_dir($configPath)) {
            return [
                'success' => false,
                'error' => __('Config directory does not exist. Please initialize JMVC first.', 'jmvc'),
            ];
        }

        // Save devalert config
        if (isset($config['devalert'])) {
            $result = self::writeDevalert($config['devalert']);
            if (!$result['success']) {
                return $result;
            }
        }

        // Save kvstore config
        if (isset($config['kvstore'])) {
            $result = self::writeKvstore($config['kvstore']);
            if (!$result['success']) {
                return $result;
            }
        }

        return ['success' => true];
    }

    /**
     * Write devalert configuration file
     *
     * @param array<string, mixed> $config
     * @return array{success: bool, error?: string}
     */
    public static function writeDevalert(array $config): array
    {
        $data = [
            'mail' => [
                'email' => sanitize_email($config['email'] ?? ''),
            ],
            'slack' => [
                'username' => sanitize_text_field($config['slack_username'] ?? 'JMVC Alert'),
                'channel' => sanitize_text_field($config['slack_channel'] ?? '#devalerts'),
                'endpoint' => esc_url_raw($config['slack_endpoint'] ?? ''),
            ],
        ];

        return self::writeConfigFile('devalert.php', 'devalert', $data);
    }

    /**
     * Write kvstore configuration file
     *
     * @param array<string, mixed> $config
     * @return array{success: bool, error?: string}
     */
    public static function writeKvstore(array $config): array
    {
        $type = $config['type'] ?? 'sqlite';

        // Validate type
        if (!in_array($type, ['sqlite', 'redis'], true)) {
            $type = 'sqlite';
        }

        $data = [
            'type' => $type,
        ];

        return self::writeConfigFile('kvstore.php', 'kvstore', $data);
    }

    /**
     * Write a configuration file
     *
     * @param string $filename
     * @param string $key
     * @param array<string, mixed> $data
     * @return array{success: bool, error?: string}
     */
    private static function writeConfigFile(string $filename, string $key, array $data): array
    {
        $path = Admin::getThemeJmvcPath() . 'config/' . $filename;

        $content = "<?php\n";
        $content .= "/**\n";
        $content .= " * " . ucfirst($key) . " Configuration\n";
        $content .= " * Generated by JMVC Admin on " . date('Y-m-d H:i:s') . "\n";
        $content .= " */\n\n";
        $content .= "JConfig::set('" . $key . "', " . self::varExport($data, 0) . ");\n";

        if (file_put_contents($path, $content) === false) {
            return [
                'success' => false,
                'error' => sprintf(__('Could not write config file: %s', 'jmvc'), $filename),
            ];
        }

        return ['success' => true];
    }

    /**
     * Pretty var_export for arrays
     *
     * @param mixed $data
     * @param int $indent
     * @return string
     */
    private static function varExport(mixed $data, int $indent = 0): string
    {
        if (!is_array($data)) {
            return var_export($data, true);
        }

        $spaces = str_repeat('    ', $indent);
        $innerSpaces = str_repeat('    ', $indent + 1);

        $output = "[\n";

        foreach ($data as $key => $value) {
            $output .= $innerSpaces;
            $output .= "'" . $key . "' => ";

            if (is_array($value)) {
                $output .= self::varExport($value, $indent + 1);
            } else {
                $output .= var_export($value, true);
            }

            $output .= ",\n";
        }

        $output .= $spaces . "]";

        return $output;
    }

    /**
     * Read current configuration from files
     *
     * @return array<string, mixed>
     */
    public static function readConfig(): array
    {
        $config = [
            'devalert' => [
                'email' => '',
                'slack_username' => 'JMVC Alert',
                'slack_channel' => '#devalerts',
                'slack_endpoint' => '',
            ],
            'kvstore' => [
                'type' => 'sqlite',
            ],
        ];

        $configPath = Admin::getThemeJmvcPath() . 'config/';

        // Parse devalert.php
        $devalertPath = $configPath . 'devalert.php';
        if (file_exists($devalertPath)) {
            $devalertConfig = self::parseConfigFile($devalertPath, 'devalert');
            if ($devalertConfig) {
                $config['devalert']['email'] = $devalertConfig['mail']['email'] ?? '';
                $config['devalert']['slack_username'] = $devalertConfig['slack']['username'] ?? 'JMVC Alert';
                $config['devalert']['slack_channel'] = $devalertConfig['slack']['channel'] ?? '#devalerts';
                $config['devalert']['slack_endpoint'] = $devalertConfig['slack']['endpoint'] ?? '';
            }
        }

        // Parse kvstore.php
        $kvstorePath = $configPath . 'kvstore.php';
        if (file_exists($kvstorePath)) {
            $kvstoreConfig = self::parseConfigFile($kvstorePath, 'kvstore');
            if ($kvstoreConfig) {
                $config['kvstore']['type'] = $kvstoreConfig['type'] ?? 'sqlite';
            }
        }

        return $config;
    }

    /**
     * Parse a config file to extract values
     *
     * @param string $path
     * @param string $key
     * @return array<string, mixed>|null
     */
    private static function parseConfigFile(string $path, string $key): ?array
    {
        $content = file_get_contents($path);
        if ($content === false) {
            return null;
        }

        // Use regex to extract the array from JConfig::set call
        $pattern = "/JConfig::set\s*\(\s*'" . preg_quote($key, '/') . "'\s*,\s*(\[[\s\S]*?\])\s*\)/";

        if (preg_match($pattern, $content, $matches)) {
            // Safely evaluate the array
            try {
                $array = eval('return ' . $matches[1] . ';');
                return is_array($array) ? $array : null;
            } catch (\Throwable $e) {
                return null;
            }
        }

        return null;
    }
}
