<?php
/**
 * JMVC Installer - Scaffolding installation logic
 *
 * @package JMVC\Admin
 */

declare(strict_types=1);

namespace JMVC\Admin;

/**
 * Handles JMVC installation to child theme
 */
class Installer
{
    /**
     * Directories to create in theme
     */
    private const DIRECTORIES = [
        'controllers/pub',
        'controllers/admin',
        'controllers/resource',
        'models',
        'views',
        'config',
    ];

    /**
     * Install JMVC scaffolding to active theme
     *
     * @return array{success: bool, error?: string}
     */
    public static function install(): array
    {
        $basePath = Admin::getThemeJmvcPath();

        // Create base directory
        if (!self::createDirectory($basePath)) {
            return [
                'success' => false,
                'error' => sprintf(__('Could not create directory: %s', 'jmvc'), $basePath),
            ];
        }

        // Create subdirectories
        foreach (self::DIRECTORIES as $dir) {
            $path = $basePath . $dir;
            if (!self::createDirectory($path)) {
                return [
                    'success' => false,
                    'error' => sprintf(__('Could not create directory: %s', 'jmvc'), $path),
                ];
            }

            // Add .gitkeep to empty directories
            $gitkeep = $path . '/.gitkeep';
            if (!file_exists($gitkeep)) {
                file_put_contents($gitkeep, '');
            }
        }

        // Copy composer.json
        $composerResult = self::copyComposerJson();
        if (!$composerResult['success']) {
            return $composerResult;
        }

        // Create default config files
        $configResult = self::createDefaultConfigs();
        if (!$configResult['success']) {
            return $configResult;
        }

        return ['success' => true];
    }

    /**
     * Create directory if it doesn't exist
     */
    private static function createDirectory(string $path): bool
    {
        if (is_dir($path)) {
            return true;
        }

        return wp_mkdir_p($path);
    }

    /**
     * Copy composer.json to theme
     *
     * @return array{success: bool, error?: string}
     */
    private static function copyComposerJson(): array
    {
        $source = JMVC_PLUGIN_PATH . 'composer.json';
        $dest = Admin::getThemeJmvcPath() . 'composer.json';

        if (file_exists($dest)) {
            return ['success' => true];
        }

        if (!file_exists($source)) {
            return [
                'success' => false,
                'error' => __('Source composer.json not found', 'jmvc'),
            ];
        }

        $content = file_get_contents($source);
        if ($content === false) {
            return [
                'success' => false,
                'error' => __('Could not read composer.json', 'jmvc'),
            ];
        }

        if (file_put_contents($dest, $content) === false) {
            return [
                'success' => false,
                'error' => __('Could not write composer.json', 'jmvc'),
            ];
        }

        return ['success' => true];
    }

    /**
     * Create default configuration files
     *
     * @return array{success: bool, error?: string}
     */
    private static function createDefaultConfigs(): array
    {
        $configPath = Admin::getThemeJmvcPath() . 'config/';

        // Default devalert.php
        $devalertContent = <<<'PHP'
<?php
/**
 * Developer Alerts Configuration
 * Generated by JMVC Admin
 */

JConfig::set('devalert', [
    'mail' => [
        'email' => '',
    ],
    'slack' => [
        'username' => 'JMVC Alert',
        'channel' => '#devalerts',
        'endpoint' => '',
    ],
]);
PHP;

        // Default kvstore.php
        $kvstoreContent = <<<'PHP'
<?php
/**
 * Key-Value Store Configuration
 * Generated by JMVC Admin
 */

JConfig::set('kvstore', [
    'type' => 'sqlite',
]);
PHP;

        // Write config files
        $configs = [
            'devalert.php' => $devalertContent,
            'kvstore.php' => $kvstoreContent,
        ];

        foreach ($configs as $filename => $content) {
            $path = $configPath . $filename;
            if (!file_exists($path)) {
                if (file_put_contents($path, $content) === false) {
                    return [
                        'success' => false,
                        'error' => sprintf(__('Could not write config file: %s', 'jmvc'), $filename),
                    ];
                }
            }
        }

        return ['success' => true];
    }

    /**
     * Install composer dependencies
     *
     * @return array{success: bool, error?: string, instructions?: string, output?: string}
     */
    public static function installDependencies(): array
    {
        $themePath = Admin::getThemeJmvcPath();

        // Check if composer.json exists
        if (!file_exists($themePath . 'composer.json')) {
            return [
                'success' => false,
                'error' => __('composer.json not found. Please initialize JMVC first.', 'jmvc'),
            ];
        }

        // Check if shell_exec is available
        if (!function_exists('shell_exec') || self::isShellExecDisabled()) {
            return [
                'success' => false,
                'error' => __('Shell execution is disabled on this server.', 'jmvc'),
                'instructions' => self::getManualInstructions($themePath),
            ];
        }

        // Try to run composer install
        $originalDir = getcwd();
        chdir($themePath);

        $output = shell_exec('composer install --no-dev --optimize-autoloader 2>&1');

        chdir($originalDir);

        // Check if vendor directory was created
        if (is_dir($themePath . 'vendor')) {
            return [
                'success' => true,
                'output' => $output,
            ];
        }

        return [
            'success' => false,
            'error' => __('Composer install failed.', 'jmvc'),
            'output' => $output,
            'instructions' => self::getManualInstructions($themePath),
        ];
    }

    /**
     * Check if shell_exec is disabled
     */
    private static function isShellExecDisabled(): bool
    {
        $disabled = explode(',', ini_get('disable_functions'));
        return in_array('shell_exec', array_map('trim', $disabled), true);
    }

    /**
     * Get manual installation instructions
     */
    private static function getManualInstructions(string $path): string
    {
        return sprintf(
            __("Run the following commands in your terminal:\n\ncd %s\ncomposer install --no-dev --optimize-autoloader", 'jmvc'),
            $path
        );
    }
}
